### PR TITLE
New Qsabers

### PR DESCRIPTION
**Pull request by Brinch-1**

### CODE REVIEW

**Comment by BeatReaper** [comment]
can you make plasma katana Qsabers please I really want that saber also can you update the saber trails
and update the plasma katana saber trail, please

**Comment by RedBrumbler** [comment]
> 
> 
> can you make plasma katana Qsabers please I really want that saber also can you update the saber trails
> and update the plasma katana saber trail, please

plasma katana will be a thing once qsaber has custom trails, and the katana trail is not outdated so I don't see the need to update it

**Comment by BeatReaper** [comment]
> > can you make plasma katana Qsabers please I really want that saber also can you update the saber trails
> > and update the plasma katana saber trail, please
> 
> plasma katana will be a thing once qsaber has custom trails, and the katana trail is not outdated so I don't see the need to update it

the plasma katana trail won't activate though and I don't know why but a lot of other not outdated mods wont work for me

**Comment by RedBrumbler** [comment]
If your bmbf is unable to enable asset mods (and some qsabers) on 1.10, your assets locator file may be missing or not updated, put the contents of this webpage in a file named `locator-assets.json` and put it in the BMBFdata folder. <https://github.com/BMBF/resources/raw/master/assets/locator-assets.json>

if it already exists then just overwrite it with this, or delete it first and then put this file in there

**Comment by BeatReaper** [comment]
> If your bmbf is unable to enable asset mods (and some qsabers) on 1.10, your assets locator file may be missing or not updated, put the contents of this webpage in a file named `locator-assets.json` and put it in the BMBFdata folder. https://github.com/BMBF/resources/raw/master/assets/locator-assets.json
> 
> if it already exists then just overwrite it with this, or delete it first and then put this file in there

I fixed it in an easy way I just downloaded the zip and extract files and went into the bmbfmod.json and opened it with notepad change some of the codings in it and clicked add to archive then uploaded it to bmbf

**Comment by RedBrumbler** [comment]
That's not the easy way, that's the unintended way

**Comment by BeatReaper** [comment]
> That's not the easy way, that's the unintended way

well... it's easy for me but I didn't try the way to you told me to try so it's really the only way I know how to fix it also I have a quick question how would I make an updated version of a saber?

**Pull request merged**
